# Generated by Django 4.2.7 on 2023-11-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='likesCount',
        ),
        migrations.AddField(
            model_name='posts',
            name='likesCount',
            field=models.IntegerField(default=0),
        ),
    ]
