# Generated by Django 4.2.7 on 2023-11-25 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_followers_follower_remove_followers_following_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='followers',
            name='following',
        ),
        migrations.AddField(
            model_name='followers',
            name='follower',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='core.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followers',
            name='following',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='core.profile'),
            preserve_default=False,
        ),
    ]
